// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BenhAnAddBenhNavigation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BenhAnAddBenhNavigation));
        
        string IMigrationMetadata.Id
        {
            get { return "202112261013048_BenhAn-Add-Benh-Navigation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
