// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BenhAnChangeNavigationToId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BenhAnChangeNavigationToId));
        
        string IMigrationMetadata.Id
        {
            get { return "202112260545134_BenhAn-Change-Navigation-To-Id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
